language: ruby
rvm:
  - 2.0
  - 2.3
script: rspec spec
before_install:
  - sudo apt-get install make gcc gfortran
  - curl -o wgrib2.tgz http://www.ftp.cpc.ncep.noaa.gov/wd51we/wgrib2/wgrib2.tgz
  - tar -xzvf wgrib2.tgz
  - cd grib2
  - export CC=gcc
  - export FC=gfortran
  - make
  - sudo cp wgrib2/wgrib2 /usr/local/bin/
